"""Reproducible methods numbers: every quantitative claim in the Methods section, generated
from the release artifacts and emitted as (a) results/methods_numbers.json and (b)
results/methods_numbers.tex — \\newcommand macros to \\input in the paper so prose can't drift.
Rerun after any filter/pipeline change. Constants echoed from code are cross-checked here.
usage: python src/make_methods_numbers.py"""
import json
from pathlib import Path

import numpy as np
import pandas as pd

O = Path("/ccn2b/dataset/babyview/2026.1/outputs")
n = {}

# release + registry
at = pd.read_csv(O / "videos_airtable_2026-07-24.csv", low_memory=False)
at = at[at.release.astype(str).str.contains("2026.1", na=False)].copy()
at["video_id"] = at.unique_video_id.astype(str)
idx = pd.read_csv(O / "release_index.tsv", sep="\t")
reg = idx.merge(at[["video_id"]].assign(
    hours=pd.to_numeric(at.duration_hours, errors="coerce").values), left_on="rec_id",
    right_on="video_id", how="left", suffixes=("", "_at"))
n["ReleaseVideos"] = len(idx)
n["ReleaseChildren"] = int(idx.subject_id.nunique())
n["ReleaseHours"] = round(float(reg.hours.sum()))

# the audio-based English filter
dec = pd.read_csv(O / "annotations/language/audio/video_decisions_audio_2026.1.csv")
keep = set(dec.loc[dec.decision != "drop-non-english", "video_id"])
n["FilterVideosDropped"] = int((dec.decision == "drop-non-english").sum())
kept = reg[reg.video_id_at.isin(set(idx.rec_id)) & reg.video_id.isin(keep)] if False else reg[reg.video_id.isin(keep)]
P = pd.read_parquet("manifests/bv26_pairs_en_audio.parquet")
kids = P.video_id.str.split("_").str[0]
n["FinalChildren"] = int(kids.nunique())
kv = reg[reg.video_id.isin(set(P.video_id))]
n["FinalHours"] = round(float(kv.hours.sum()))
per_child = kv.assign(child=kv.video_id.str.split("_").str[0]).groupby("child").hours.sum()
n["FinalChildHoursMin"] = round(float(per_child.min()), 1)
n["FinalChildHoursMax"] = round(float(per_child.max()), 1)
n["FinalPairs"] = len(P)
n["FinalFrames"] = int(P.groupby(["video_id", "frame_idx"]).ngroups)

# referent annotation
g = pd.read_parquet(O / "annotations/referent/gemini_2026.1.parquet", columns=["alignment"])
a = g.alignment.dropna()
n["AlignZeroPct"] = round(float((a == 0).mean() * 100), 1)
n["AlignMidPct"] = round(float(((a > 0) & (a < 50)).mean() * 100), 1)
n["AlignHighPct"] = round(float((a >= 50).mean() * 100), 1)

# model config (cross-checked against a final run's metrics)
m = json.load(open("runs/F_dinov3l_base_s0/metrics.json"))
n["Vocab"] = m["vocab"]
n["TrainPairsEffective"] = m["n_pairs"]
n["Epochs"] = m["epochs"]
src = open("src/train_frame_mil.py").read()
assert 'default=3e-4' in src and "AdamW" in src and 'default=256' in src
n["LR"] = "3e-4"; n["Batch"] = 256; n["WeightDecay"] = 0.1
n["DevCategories"] = 117; n["TestCategories"] = 60; n["EmbedDimHead"] = 512; n["Regions"] = 16

Path("results").mkdir(exist_ok=True)
Path("results/methods_numbers.json").write_text(json.dumps(n, indent=2))
with open("results/methods_numbers.tex", "w") as f:
    f.write("% AUTO-GENERATED by src/make_methods_numbers.py — do not edit; \\input in the paper\n")
    for k, v in n.items():
        vv = f"{v:,}" if isinstance(v, int) and abs(v) > 999 else str(v)
        f.write(f"\\newcommand{{\\M{k}}}{{{vv}}}\n")
print(json.dumps(n, indent=1))
